### ISSUE TITLE
Associating healthcare professionals with companies and patients

### ISSUE THREAD

**Issue by NathaelB** [libreconnect/backend#20]
Set up relationships between healthcare professionals, companies (hospitals, clinics) and patients. Each healthcare professional must be able to be linked to one or more companies, as well as to specific patients.

## Tasks & Specs

- [ ] Model relationships in the database:
    - [ ] Many-to-many relationship between `Professional` and `Company` (a professional can be associated with several companies).
    - Many-to-many relationship between `Professional` and `Patient` (a professional can follow several patients and vice versa).
- [ ] Add methods to models to manage these relationships.
- [ ] Update CRUD endpoints to allow association with companies and patients:
    - [ ] Enable companies to be selected and managed when creating/updating a professional.
    - [ ] Enable patients to be assigned or removed for a specific professional.
- [ ] Test associations to ensure that data is correctly linked and retrievable.

### Endpoints API for Managing Associations
- [ ] Associate a Professional with a Company
   - Endpoint: `POST /professionals/{professional_id}/companies`
   - Body:
   ```json
   {
     "company_ids": ["1", "2", "3"]
   }
   ```
   - Feature:
      - Associates a professional with the companies listed in `company_ids`
      - Be sure to check that company IDs exist before associating them
- [ ] Associate a Professional with a Patient:
   - Endpoint: `POST /professionals/{professional_id}/patients`
   - Body:
   ```json
   {
     "patient_ids": ["2", "3"]
   }
   ```
   - Feature:
      - Associates a professional with patients listed in `patient_ids`
      - Be sure to check that patient IDs exist before associating them
- [ ] Retrieve Companies from a Professional:
  - Endpoint: `GET /professionals/{professional_id}/companies`
  - Functionality:
     - Returns the list of companies associated with this professional (paginated)
- [ ] Retrieve Patients from a Professional
   - Endpoint: `GET /professionals/{professional_id}/patients`
   - Functionality:
      - Returns the list of patients associated with this professional.
- [ ] Delete an Association between a Professional and a Company
   - Endpoint: `DELETE /professionals/{professional_id}/companies/{company_id}`
   - Functionality :
      - Deletes the association between the professional and the specified company.
- [ ] Delete an Association between a Professional and a Patient
   - Endpoint : `DELETE /professionals/{professional_id}/patients/{patient_id}`
   - Functionality:
      - Deletes the association between the specified professional and patient. 

### Data validation

- [ ] Validation during Creation/Update
   - [ ] Ensure that the `company_ids` and `patient_ids` IDs sent actually exist in the corresponding tables.
   - [ ] Add clear error messages if an association attempt fails due to invalid data.
- Permission Control
   - [ ] Check that only an administrator or professional with the necessary rights can make changes to these associations.
   - [ ] Implement validation tests to ensure that users cannot associate professionals with companies or patients to which they should not have access.

### Unit and Integration Testing
- [ ] Unit testing
   - [ ] Create tests to check that relationships are properly established and managed in the models
   - [ ] Test the methods of the services in question
- [ ] Integration testing
   - [ ] Create tests for endpoints created/modified, ensuring that associations are made correctly.
   - [ ] Include test cases for scenarios where relationships need to be deleted, and check that this works without leaving orphaned data.
   - [ ] Test error scenarios, such as invalid IDs or lack of permissions.

## Deliverables
- Models and migrations updated with appropriate relationships.
API endpoints created to manage associations.
- Unit and integration tests validating the correct operation of the associations.
- Documentation updated to include new API routes and information on managing relationships between professionals, companies and patients.
