### ISSUE TITLE
Set up a Specific Role System for Professionals (Doctors, Nurses, etc.)

### ISSUE THREAD

**Issue by NathaelB** [libreconnect/backend#21]
Implement a system of specific roles for healthcare professionals, enabling access and authorisations to be differentiated according to the professional's role (e.g. doctor, nurse, medical administrator).

## Tasks
- [ ] Define the roles in the system (e.g. `Doctor`, `Nurse`, ...)
- [ ] Create a `role` field in the `Professional` model to store the role of each user.
- [ ] Adapt access controls according to role
   - For example, only `Doctors` can prescribe medicines or access certain types of sensitive data
   - Depending on the doctor's speciality, access to a patient's data can be restricted, e.g. a `diabetes specialist` will have preferential access to a diabetic's data.
   - Enable modular access to data, with the addition of an audit to find out what is happening at each interaction and enable data to be shared between professionals (e.g. a doctor needs to know the health assessment of a diabetic in order to prescribe certain medicines).
- [ ] Set up validations to ensure that the actions of professionals are consistent with their role.
- [ ] Test to check that role-based restrictions are working correctly.
